name = "gudang-roti-boss-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "roti-boss-gudang"
database_id = "4fac695c-a0c7-4288-9ea3-b3174e3a9220"

[triggers]
crons = ["*/4 * * * *"]   # setiap 4 menit warm-up
